spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"

---
spring:
  config:
    activate:
      on-profile: "local"
      # todo : should encapsulation
  datasource:
    url: "jdbc:mariadb://localhost:3306/paper_route"
    username: "pruser"
    password: "root1234"
---

spring:
  config:
    activate:
      on-profile: "common"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    database: sql-server

#logging: level:
#    org.hibernate:
#      type.descriptor: trace
#      SQL: DEBUG